### PR TITLE
Handing bedfile headers

### PR DESCRIPTION
**Pull request by Lmercadom**
Modify convert.py script to allow multicolumn row_infos files
Modify multivec.py script to handle bedfiles with headers automatically

Right now the code works for one input file only. When there is more than one file, This line: https://github.com/4dn-dcic/clodius/blob/d97d7a522cba5a0e76cbd99f310e587bcd35b734/clodius/multivec.py#L40

assumes that all the files have the same headers and the same binsizes. This could be problematic because we previously modify the code to allow files with different binsizes, and also there could be files with or without headers or different types of headers.

There is also an issue with the file format. The code allows both gzipped and unzipped files as inputs. However, the code seems only to be handling the gzipped format.

### CODE REVIEW

**Comment by burakalver** [comment]
Just the clarify. Both issues (multiple bed files assumed to have exactly matching rows, and non-gzipped files being read as text vs. gzipped files being read as binary) are present before or after the PR. The PR does not introduce or address these issues.

**Comment by pkerpedjiev** [comment]
Hi Luisa and Burak, thanks for the PR!

Would you mind adding a test to make sure that your changes work as expected?

Also, is it not possible to keep the `--has-header` option and also automatically detect standard bedfile headers? Why are you removing it? My apologies if we discussed this on Slack and I don't remember.

**Comment by Lmercadom** [comment]
Hi Pete, I added the test. We could keep the `has-header` option, the problem with that is that right now it only removes the first line of the file. So it would only work with files that have one line headers and it also needs to be specified by the user. So, it requires extra handling from the user, and we thought that if nobody was using it, it would be better/cleaner to remove it altogether.

**Comment by pkerpedjiev** [comment]
Cool, thanks for the test. There are actually cases where it's being used. Sorry if I said otherwise earlier. It's actually not uncommon for files to contain single line column headers. This usually happens when the file isn't exactly a bed file but looks close enough to one that we'd like to treat it as such.

**Comment by pkerpedjiev** [comment]
So just to be clear, `--has-header` should be kept. So the regular bedfile annotations that you're removing should be removed and then if `--has-header` is present, it should remove the first line. If there's bedfile annotations that you remove *and** `--has-header` is present, then it should either remove the first remaining line or not do anything. Up to you to decide which you think is more reasonable.

**Comment by Lmercadom** [comment]
The line of code that runs the `--has-header` flag runs before removing the bedfile headers, so if there is a bedfile with annotations and the `--has-header` flag, the has-header flag will remove the first line and the code that removes bedfile headers would remove the remaining lines in case there are more and would not do anything in case there is only one. So I will add back the `--has-header` option where it was initially located.

**Pull request merged**
