### PR TITLE
Add tiles function in tiles.multivec

### PR DESCRIPTION
**Pull request by zhqu1148980644**
## Description

What was changed in this pull request?
Add `tiles` in tiles.multivec.

Why is it necessary?
This function can be used in `higlass-python` and `higlass server`.

Fixes #___

## Checklist

- [x] Unit tests added or updated
- [ ] Updated CHANGELOG.md

### CODE REVIEW

**Comment by pkerpedjiev** [comment]
Hey, thanks for the PR!

Would you mind adding a test to verify that it works as intended? It should go in here: https://github.com/higlass/clodius/blob/develop/test/multivec_test.py

You can see some other examples of tile generation tests here: https://github.com/higlass/clodius/blob/c3cad938a8b425c7a1e6c297570bad0fff9f88ae/test/tiles/bigwig_test.py#L13

(multivec tiles don't use the `.min` and `.max` suffixes in the tile identifiers though)

**Comment by zhqu1148980644** [comment]
Why shouldn't we put it in  https://github.com/higlass/clodius/blob/develop/test/tiles/multivec_test.py

**Comment by zhqu1148980644** [comment]
I think https://github.com/higlass/clodius/blob/develop/test/tiles/multivec_test.py may be more suitable for holding this test.

**Comment by pkerpedjiev** [comment]
Ah yes. You're right. That is more suitable.

**Comment by pkerpedjiev** [comment]
Your changes look good. Want to update the `CHANGELOG.md` with an entry for `v0.11.5` and I can approve and merge them?

**Comment by zhqu1148980644** [comment]
I think I can add some more tiles function. Can I update the `CHANGELOG.md` later?

**Comment by pkerpedjiev** [comment]
> Can I update the CHANGELOG.md later?

Are you planning on adding the other tiles functions in this PR or another? If in this PR then feel free to update the CHANGELOG later. If it's in another PR, then I think it would be easier to just update the CHANGELOG here, close this PR out and update it again in the other PR.

I would personally prefer having multiple PRs but it's up to you :-)

**Comment by zhqu1148980644** [comment]
Updated the CHANGELOG.

**Comment by pkerpedjiev** [comment]
Thanks! Should I merge or do you plan on adding anything else to this PR?

**Comment by zhqu1148980644** [comment]
I would appreciate it if you can merge this PR. :-)

**Comment by pkerpedjiev** [comment]
It will be in the next release, which should hopefully be out within a week or two.

**Pull request merged**
