### PR TITLE
Flekschas/bigwig multi value summary

### PR DESCRIPTION
**Pull request by flekschas**
## Description

> What was changed in this pull request?

Looks like I wrote a bunch of test for testing range data (i.e., multivalue data) which I never merged. 🤷‍♂️

> Why is it necessary?

Tests are always cool

## Checklist

- [x] Unit tests added or updated
- ~[ ] Updated CHANGELOG.md~

### CODE REVIEW

**Comment by nvictus** [comment]
oops. didn't mean to close this

**Comment by flekschas** [comment]
@pkerpedjiev @nvictus Do you think it makes sense to merge these tests? I can check why the PR is failing. I don't have strong feelings, I just think tests are always good. But we could also close the PR.

**Comment by pkerpedjiev** [comment]
Yes, definitely. One of the test failures was just `flake8` formatting, which I resolved. The other is a dask API issue. Not sure why it's complaining on this PR. Maybe a version mismatch.

**Comment by nvictus** [comment]
The dask issue should be solved by #108, which I merged into develop earlier today.

**Comment by flekschas** [comment]
Cool thanks. I merged develop into this PR. Let's see if that fixes the issue.

**Pull request merged**
